### PR TITLE
update for kernels >= 4.14

### PR DESCRIPTION
**Pull request by henning-schild**
remove include that is not needed anymore

Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
is this repo unmaintained?

**Comment by teleshoes** [comment]
hey, sorry.
i mean, its not unmaintained, but its not exactly NOT unmaintained either. i update it only to get tpacpi-bat working when it breaks for me personally.
ill try to take a look at this soon

**Comment by henning-schild** [comment]
Thanks, because i am working on another patch that i would like to get merged. (here?) That is also coming from tpacpi-bat.

**Comment by teleshoes** [comment]
hey look, it only took me 1 full year to actually test this! ...sorry :(

**Comment by henning-schild** [comment]
oh progress ;) thx

i do not even remember what that other patch was, interesting to see that it took you so long to adopt >= 4.15

what is "upstream" if this is potentially not?

**Comment by teleshoes** [comment]
unfortunately this is as upstream as it gets, afaik.
(`tpacpi-bat` is actually mine, `acpi_call` i only maintain because its a dependency of `tpacpi-bat`)

**Comment by henning-schild** [comment]
not sure about other distros but gentoo has both ... not sure how many users there are

https://github.com/gentoo/gentoo/tree/master/app-laptop/tpacpi-bat
https://github.com/gentoo/gentoo/tree/master/sys-power/acpi_call

maybe that helps in terms of motivation, there are people using it!
And i guess other distros like maybe arch have it as well

**Comment by teleshoes** [comment]
yea i suppose i should maintain these better. please feel free to pull-req any patches you like. i will do at least basic code review and testing on at least one thinkpad.

**Comment by Mic92** [comment]
Btw. The NixOS community also maintains a fork now. Maybe we can consolidate the effort somehow: https://github.com/mkottman/acpi_call/issues/89

**Pull request merged**
