### PR TITLE
fix build for 5.6* kernels

### PR DESCRIPTION
**Pull request by nikitosiusis**
this will make a module work in new kernels
i use it with xmm2usb script to enable modem in x1 carbon gen7

### CODE REVIEW

**Comment by teleshoes** [comment]
odd, build has been working for me all along, and still works on 5.4.18. whats the build error you see without this?

**Comment by nikitosiusis** [comment]
Hi. I might need to check the actual error on every 5.* kernel, but I checked only on latest one :(

on 5.6rc1 I get this error

```
make[1]: Entering directory '/usr/src/linux-headers-5.6.0-050600rc1-generic'
  CC [M]  /home/niko/tmp/modem-fix/acpi_call/acpi_call.o
/home/niko/tmp/modem-fix/acpi_call/acpi_call.c: In function ‘init_acpi_call’:
/home/niko/tmp/modem-fix/acpi_call/acpi_call.c:386:53: warning: passing argument 4 of ‘proc_create’ from incompatible pointer type [-Wincompatible-pointer-types]
                                                     &proc_acpi_operations);
                                                     ^
In file included from /home/niko/tmp/modem-fix/acpi_call/acpi_call.c:8:0:
./include/linux/proc_fs.h:64:24: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
 struct proc_dir_entry *proc_create(const char *name, umode_t mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
                        ^~~~~~~~~~~
  MODPOST 1 modules

```

inserting this module in kernel results in dmesg errors.
I believe it was changed in recent kernels, because I had same error with some nvidia modules also.

**Comment by nikitosiusis** [comment]
well, I've checked some sources and found different definitions 
https://elixir.bootlin.com/linux/v5.5.3/source/fs/proc/generic.c#L550
https://elixir.bootlin.com/linux/v5.6-rc1/source/fs/proc/generic.c#L548

I think that my fix is only needed for 5.6+. I will change my if condition if you'd like too :)

**Comment by teleshoes** [comment]
awesome, thanks for this very timely patch! tested, works in 5.4.18 and 5.5.3. (ill retest in 5.6 when its released)

can you squash the two commits plz? (the first commit breaks in kernels 5.0.* => 5.5.*)

**Comment by nikitosiusis** [comment]
I made a new pullrequest for that :(

**Pull request closed without merging**
